- menu_name: "其他"

- name: "联系我"
  url: "/contact/"
  title: "联系我"

- name: "RSS订阅"
  url: "/feed.xml"
  title: "RSS订阅"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
