- menu_name: "Services"

- name: "Contact"
  url: "/contact/"
  title: "联系我"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS订阅"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
